image: node:latest

stages:
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: deploy
  script:
    - sudo cp -R ./* /home/ec2-user/discordbot_zbeub
    - sudo cd node
    - sudo npm install
    - sudo cd ../
    - sudo cd python/sh
    - sudo ./install_dependencies.sh
  artifacts:
    paths:
      - node_modules/
